### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MIKASTHEBOSS** [xharky/Valorant-checker-V2#2]
Traceback (most recent call last):
  File "C:\Users\fortnite\Downloads\Valorant-checker-V2-main\Valorant-checker-V2-main\main.py", line 613, in <module>
    checker()
  File "C:\Users\fortnite\Downloads\Valorant-checker-V2-main\Valorant-checker-V2-main\main.py", line 220, in checker
    data = pattern.findall(data['response']['parameters']['uri'])[0]
KeyError: 'response'

**Comment by JokersCat** [comment]
something with your internet idk for me it works fine it is just so slow because there is no proxy support :(

**Comment by MIKASTHEBOSS** [comment]
> Its not an internet issue, I tried 3 different wifi's and it still isn't working :(
