### ISSUE TITLE
error when selecting option

### ISSUE THREAD

**Issue by Ceeazer1** [xharky/Valorant-checker-V2#4]
Traceback (most recent call last):
  File "C:\Users\Osorio\Desktop\Valorant-checker-V2-main\main.py", line 613, in <module>
    checker()
  File "C:\Users\Osorio\Desktop\Valorant-checker-V2-main\main.py", line 187, in checker
    data = r2.json()
  File "C:\Users\Osorio\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Osorio\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Osorio\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Osorio\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Prodzify** [comment]
Fixing soon

**Comment by TheCeio** [comment]
it still doesnt work :(
